name: Generate release

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Compress application
    - name: application
      if: github.event_name != 'pull_request'
      shell: pwsh
      run: Compress-Archive .\512\* 512x512.zip

    # Compress application
    - name: application
      if: github.event_name != 'pull_request'
      shell: pwsh
      run: Compress-Archive .\256\* 256x256.zip

    # Compress application
    - name: application
      if: github.event_name != 'pull_request'
      shell: pwsh
      run: Compress-Archive .\128\* 128x128.zip

    # Create release
    - name: Release 
      uses: softprops/action-gh-release@v1
      if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
      with:
        tag_name: ${{ github.run_number }}
        prerelease: false
        body: Release, compare Git commits.
        files: |
          512x125.zip
          256x256.zip
          128x128.zip
